### ISSUE TITLE
Enable user-protected profile fileds or primary auth backend

### ISSUE THREAD

**Issue by hroncok** [devassistant/dapi#1]
Currently, when I log in via Fedora or Github, my e-mail address and name is overwritten by the latest login method. While this can be disabled in python-dajngo-social on application level, I would like to solve it per user.

First approach I'm thinking of: Each filed in user profile would have a protection checkbox. If protection is enabled, user can fill in any custom data and no auth backend will overwrite it. If protection is disabled, the data are updated on every login (as it currently is).

Downside of this solution is that protected data will not be auto-upgraded when user changes the profile of the provider (e.g. changed e-mail address on Github).

Other way of achieving user comfort is to select primary backend (i.e. Fedora vs. Github, default to first used) to get the data from.

Downside is that user will not be able to fill in any custom data (i.e. use dedicated email address for Dapi). Also when user selects Fedora as primary but always logs in with Github (or vice versa), the data would be never updated.

Anyway, the following is needed for both:
- Create Profile model with OneToOne connection to the User (for storing protection flags or default backend)
- Replace `social.pipeline.user.user_details` with custom code

cc @bkabrda

**Comment by bkabrda** [comment]
I'd say that we should just save the data on first login and then let user choose from which backends (e.g. he can select more than one) the data should be updated when he logs in (defaulting to the first used login method). Makes sense?

**Comment by hroncok** [comment]
Having those fields in user profile:
- [x] When I log in in with Fedora, update my e-mail address and name
- [ ] When I log in in with Github, update my e-mail address and name

And by default set the first used backend to True and the other one to False?

That leads to one more question: Should the user be able to manually change e-mail address or name when at least one of those boxes is selected?

**Comment by bkabrda** [comment]
> And by default set the first used backend to True and the other one to False?

Yes, that's my idea.

> That leads to one more question: Should the user be able to manually change e-mail address or name when at least one of those boxes is selected?

No, that doesn't make sense. In that case, we'd have to add a functionality that would block modified fields from updating and that's an overkill right now. User should only be able to modify fields by hand if none of these checkboxes are checked.
