### ISSUE TITLE
More sophisticated search

### ISSUE THREAD

**Issue by hroncok** [devassistant/dapi#11]
Ability to search by more criteria, such as tags, licenses, users.

Ability to search users.

**Comment by tradej** [comment]
Searching should also return substrings, e. g. searching for "node" should return "nodejs". That is valid for both API and the website.

**Comment by tradej** [comment]
I would also suggest removing the **low prio** tag, as the usability of the site is severely hindered by this.

**Comment by bkabrda** [comment]
Another nice improvement of searching might be hiding DAPs that have no assistants (e.g. common_args ATM). There should be a checkbox that would make these appear again, if user wants to see them.

**Comment by hroncok** [comment]
I found out how to filter the search results with Haystack. Will provide some filtering options soon.

Currently I think of:
- Important:
  - [x] active/deactivated
  - [x] has assistants
  - [x] has stable release
  - [x] is supported on X platform
- Not so much (probably not doing all):
  - [ ] license (some licenses tags might get complicated and it would be hard to let's say search for anything GPL compatible)
  - [ ] tags (would require more complicated UI to specify how to use tags - whether to find daps that has all of them, or just some of them, etc.)
  - [x] minimal rank & minimal rank count

Other ideas?

Later I'll focus on the substring thing reported by @tradej (found something [here](http://stackoverflow.com/questions/14356405/django-haystack-module-search-with-whoosh))

**Comment by hroncok** [comment]
Demo at https://staging-devassistant.rhcloud.com/search/

**Comment by hroncok** [comment]
Now is also possible to use advanced search via the API https://staging-devassistant.rhcloud.com/api/search/

Any thoughts?

**Comment by bkabrda** [comment]
So maybe I'm doing something wrong, but how do I, for example, search for keyword "foo" and limit the results to daps that only work on Fedora? (the keyword part is what I'm missing).

Also, the "results" part of the page seems to be `[]` no matter for what I search, is that expected?

**Comment by hroncok** [comment]
In web view:

https://staging-devassistant.rhcloud.com/search/?q=foo&platform=fedora

But it gives you no results, because foo has no assistants, so you might use this:

https://staging-devassistant.rhcloud.com/search/?q=foo&noassistants=on&platform=fedora

In the API:

https://staging-devassistant.rhcloud.com/api/search/?q=foo&noassistants=on&platform=fedora (the same URL with added /api/)

Problem with staging and no results is because most of the daps are either devel version, without assistants, deactivated etc. - feel free to upload more and test then.

**Comment by bkabrda** [comment]
Ok, that's pretty good. I'd probably advise uppercasing "DAP" usage to keep consistent with documentation etc, otherwise I'm ok with the way it looks and works except for some minor issues:
- input fields probably shouldn't be stretched to the width of the whole page (platform dropdown, average rank, rank count)
- min. average rank and rank count shouldn't allow numbers below 0; average rank shouldn't allow numbers higher than 5 (just a nitpick, really :))

**Comment by hroncok** [comment]
- dap vs DAP - I kept it consistent with the whole webpage, and I will introduce a commit that will change it globally
- input fields and how they look - honestly, I have no idea, how to do that without some harakiri
- numerical limits - good point

Also, I realized that when you enter some bullshit, like platform=foobar, the web view will display an error message, but the API call will silently fail

**Comment by tradej** [comment]
Ad dap vs DAP: When changing it everywhere, please uppercase "Assistants" too (I'd be in favour of uppercasing snippets as well, but that would need adjustments in the general documentation as well).

**Comment by hroncok** [comment]
Counting on it

**Comment by hroncok** [comment]
Deployed.

**Comment by hroncok** [comment]
Not to forget the substring thing

**Comment by hroncok** [comment]
For  the substring thing:
1. I was unable to make http://stackoverflow.com/questions/14356405/django-haystack-module-search-with-whoosh work
2. current search engine uses stemming, so it will find server for serve and such. unfortunately nodejs is not stemmed to node. by using 1., this stops working.

Try for example https://dapi.devassistant.org/search/?q=provide&noassistants=on - it will find common_args, that only say "Provides" and "provided"

Or try https://dapi.devassistant.org/search/?q=present - it will find revealjs, that only says "presentation"
