### ISSUE TITLE
Limit uploaded file size

### ISSUE THREAD

**Issue by bkabrda** [devassistant/dapi#23]
We should make sure that the maximum upload size of a single DAP is limited. Let's say 5 MB for start, that should be enough for everyone (does anyone else see a similarity with a popular quote here? :))

See https://github.com/devassistant/devassistant/issues/324#issuecomment-65621443 for an initial comment on this.

**Comment by hroncok** [comment]
If anyone needs bigger dap, let us know here, we'll raise the limit.
